[package]
name = "foxglove_c"
version = "0.2.1"
edition = "2021"
publish = false

[lib]
name = "foxglove"
crate-type = ["staticlib", "cdylib"]

[lints]
workspace = true

[dependencies]
foxglove = { path = "../rust/foxglove", features = ["unstable"] }

[build-dependencies]
cbindgen = "0.28.0"
